# Generated by Django 2.2 on 2021-01-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='time',
            field=models.TextField(default=20, verbose_name='время'),
            preserve_default=False,
        ),
    ]
