# Generated by Django 2.2 on 2021-01-28 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_remove_ingredient_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='amount',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='posts.Amount'),
            preserve_default=False,
        ),
    ]
