# Generated by Django 2.2 on 2021-01-31 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_recipe_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='tag',
            new_name='tags',
        ),
    ]
