# Generated by Django 2.2 on 2021-02-01 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0025_auto_20210131_1613'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Amount',
            new_name='Number',
        ),
    ]
