# Generated by Django 2.2 on 2021-02-10 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0040_auto_20210210_1815'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ('-created',), 'verbose_name': 'Избранное'},
        ),
    ]
