# Generated by Django 2.2 on 2021-02-14 13:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0044_auto_20210214_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='amount',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
