# Generated by Django 2.2 on 2021-02-14 13:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0045_auto_20210214_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='amount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
